import React from "react";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import Tabs from "@/components/Tabs/Tabs";
import Head from "next/head";
import style from "@/styles/MyProfile.module.scss";
import ShowCollection from "@/components/ShowCollection/ShowCollection";
import { useState, useEffect } from "react";
import axios from "axios";

import { GlobalVariables } from "./_app";
import { useContext } from "react";

const removeNullValFromArr = (arr) => {
  let result = [];
  for (let index = 0; index < arr.length; index++) {
    const element = arr[index];
    if (element !== null || element === undefined) {
      result.push(element);
    }
  }
  return result;
};

const RecentlyVisited = () => {
  const { ClientData, setClientData, AvatarCollection } =
    useContext(GlobalVariables);
  const [SuggestionsCollection, setSuggestionsCollection] = useState([]);

  useEffect(() => {
    // Getting Updated user data
    axios
      .post("/api/get-user", {
        username: ClientData.username,
        password: ClientData.password,
      })
      .then(function (response) {
        setClientData(response.data[0]);
        console.log(ClientData);
        axios
          .post("/api/get-specific-shows", ClientData.RecentlyVisited)
          .then(function (response) {
            setSuggestionsCollection(removeNullValFromArr(response.data));
            console.log({ SuggestionsCollection });
          })
          .catch(function (error) {
            console.log(error);
          })
          .finally(function () {});
      })
      .catch(function (error) {
        setClientData({});
        console.log(error);
        alert("Error Authentication, Please Login Again");
      })
      .finally(function () {});
  }, []);

  return (
    <>
      <Head>
        <title>AnimixPlay</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={style.main}>
        <h1
          style={{
            display: "flex",
            alignItems: "center",
            fontSize: "1.8rem",
            marginBottom: "1.6rem",
            marginLeft: "1.1rem",
          }}
        >
          <svg
            style={{
              color: "#07bf67",
              width: "35px",
              aspectRatio: "1/1",
              objectFit: "contain",
              marginRight: "0.7rem",
            }}
            class="svg-icon"
            viewBox="0 0 1024 1024"
            version="1.1"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              d="M293.376 645.290667A256.085333 256.085333 0 0 0 753.408 597.333333h89.173333a341.461333 341.461333 0 0 1-610.816 109.568L128 810.666667v-256h256l-90.624 90.624z m437.290667-266.624A256.170667 256.170667 0 0 0 270.506667 426.666667H181.333333a341.546667 341.546667 0 0 1 610.986667-109.653334L896 213.333333v256h-256l90.666667-90.666666z"
              fill="#07bf67"
            />
          </svg>
          Continue
        </h1>
        <br />
        <ShowCollection
          ShowList={SuggestionsCollection}
          CrossButtonStatus={false}
          CrossButtonFunction={() => {}}
          maxWidth={"1200px"}
        />
      </main>
      <Footer />
    </>
  );
};

export default RecentlyVisited;
