import React, { useState } from "react";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import Tabs from "@/components/Tabs/Tabs";
import Head from "next/head";
import style from "@/styles/MyProfile.module.scss";
import { GlobalVariables } from "./_app";
import { useContext } from "react";
import axios from "axios";

const MyProfile = () => {
  const { ClientData, setClientData, AvatarCollection } =
    useContext(GlobalVariables);

  useState(() => {
    axios
      .post("/api/get-user", {
        username: ClientData.username,
        password: ClientData.password,
      })
      .then(function (response) {
        setClientData(response.data[0]);
      })
      .catch(function (error) {
        setClientData({});
        console.log(error);
        alert("Error Authenticating, Please Login Again");
      })
      .finally(function () {});
  }, []);

  return (
    <>
      <Head>
        <title>AnimixPlay</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={style.main}>
        <div className={style.Profile}>
          <h1>Profile</h1>

          <div className={style.ProfileBox}>
            <div className={style.col1}>
              <label>First Name</label>
              <input type="text" value={ClientData.first_name} />
              <label>Last Name</label>
              <input type="text" value={ClientData.last_name} />
              <label>User Name</label>
              <input type="text" value={ClientData.username} />
              <label>Email</label>
              <input type="text" value={ClientData.email} />
            </div>
            <div className={style.col2}>
              <img
                src={AvatarCollection[ClientData.profile_image_index]}
                alt=""
              />
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
};

export default MyProfile;
