import React from "react";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import Tabs from "@/components/Tabs/Tabs";
import Head from "next/head";
import style from "@/styles/MyProfile.module.scss";
import ShowCollection from "@/components/ShowCollection/ShowCollection";
import { useState, useEffect } from "react";
import axios from "axios";

import { GlobalVariables } from "./_app";
import { useContext } from "react";

const removeValue = (arr, value) => {
  const filteredArray = arr.filter((item) => {
    return item !== value;
  });
  return filteredArray;
};

const removeNullValFromArr = (arr) => {
  let result = [];
  for (let index = 0; index < arr.length; index++) {
    const element = arr[index];
    if (element !== null || element === undefined) {
      result.push(element);
    }
  }
  return result;
};

const WatchList = () => {
  const { ClientData, setClientData, AvatarCollection } =
    useContext(GlobalVariables);
  const [SuggestionsCollection, setSuggestionsCollection] = useState([]);

  useEffect(() => {
    // Getting Updated user data
    axios
      .post("/api/get-user", {
        username: ClientData.username,
        password: ClientData.password,
      })
      .then(function (response) {
        setClientData(response.data[0]);
        console.log(ClientData);
        axios
          .post("/api/get-specific-shows", ClientData.WatchList)
          .then(function (response) {
            setSuggestionsCollection(removeNullValFromArr(response.data));
            console.log({ SuggestionsCollection });
          })
          .catch(function (error) {
            console.log(error);
          })
          .finally(function () {});
      })
      .catch(function (error) {
        setClientData({});
        console.log(error);
        alert("Error Authentication, Please Login Again");
      })
      .finally(function () {});
  }, []);

  const RemoveFromList = (showId) => {
    // Getting Updated user data
    axios
      .post("/api/get-user", {
        username: ClientData.username,
        password: ClientData.password,
      })
      .then(function (response) {
        setClientData(response.data[0]);
        console.log(ClientData);

        // Getting Updated user data
        axios
          .post("/api/update-user", {
            username: ClientData.username,
            password: ClientData.password,
            update: {
              WatchList: removeValue(ClientData.WatchList, showId),
            },
          })
          .then(function (response) {
            setClientData(response.data.New[0]);
            console.clear();
            console.log({ ClientData, New: response.data.New[0].WatchList });
            axios
              .post("/api/get-specific-shows", response.data.New[0].WatchList)
              .then(function (response) {
                setSuggestionsCollection(removeNullValFromArr(response.data));
                console.log({ seg: SuggestionsCollection });
              })
              .catch(function (error) {
                console.log(error);
              })
              .finally(function () {});
          })
          .catch(function (error) {
            setClientData({});
            console.log({ error });
            alert("Error Authentication, Please Login Again");
          })
          .finally(function () {});
      })
      .catch(function (error) {
        setClientData({});
        console.log(error);
        alert("Error Authentication, Please Login Again");
      })
      .finally(function () {});
  };

  return (
    <>
      <Head>
        <title>AnimixPlay</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={style.main}>
        <h1
          style={{
            display: "flex",
            alignItems: "center",
            fontSize: "1.8rem",
            marginBottom: "1.6rem",
            marginLeft: "1.1rem",
          }}
        >
          <svg
            style={{
              color: "#07bf67",
              width: "40px",
              aspectRatio: "1/1",
              objectFit: "contain",
              marginRight: "0.7rem",
              transform: "translateY(5px)",
            }}
            xmlns="http://www.w3.org/2000/svg"
            version="1.1"
            x="0px"
            y="0px"
            viewBox="0 0 68 85"
          >
            <g>
              <path
                fill="#07bf67"
                d="M10.8399048,28.8200684h7.9101563c1.2799072,0,2.3199463-1.0498047,2.3199463-2.3398438v-5.8901367   c0-1.2900391-1.0400391-2.3398438-2.3199463-2.3398438h-7.9101563c-1.2799072,0-2.3199463,1.0498047-2.3199463,2.3398438v5.8901367   C8.5199585,27.7702637,9.5599976,28.8200684,10.8399048,28.8200684z M12.6199341,22.0700684   c0-0.7202148,0.7800293-1.1601563,1.3900146-0.7797852l2.5500488,1.5595703c0.5799561,0.3500977,0.5799561,1.2001953,0,1.5600586   l-2.5500488,1.5600586c-0.6099854,0.3701172-1.3900146-0.0698242-1.3900146-0.7797852V22.0700684z"
              />
              <path
                fill="#07bf67"
                d="M10.8399048,41.9001465h7.9101563c1.2799072,0,2.3199463-1.050293,2.3199463-2.3300781V33.670166   c0-1.2802734-1.0400391-2.3300781-2.3199463-2.3300781h-7.9101563c-1.2799072,0-2.3199463,1.0498047-2.3199463,2.3300781v5.8999023   C8.5199585,40.8498535,9.5599976,41.9001465,10.8399048,41.9001465z M12.6199341,34.880127   c0-0.7099609,0.7800293-1.1499023,1.3900146-0.7802734l2.5500488,1.5600586c0.5799561,0.3603516,0.5799561,1.2001953,0,1.5600586   l-2.5500488,1.5600586c-0.6099854,0.3701172-1.3900146-0.0698242-1.3900146-0.7797852V34.880127z"
              />
              <path
                fill="#07bf67"
                d="M10.8399048,54.9899902h7.9101563c1.2799072,0,2.3199463-1.0400391,2.3199463-2.3300781v-5.8999023   c0-1.2797852-1.0400391-2.3300781-2.3199463-2.3300781h-7.9101563c-1.2799072,0-2.3199463,1.050293-2.3199463,2.3300781v5.8999023   C8.5199585,53.9499512,9.5599976,54.9899902,10.8399048,54.9899902z M12.6199341,47.880127   c0-0.7099609,0.7800293-1.1499023,1.3900146-0.7802734l2.5500488,1.5600586c0.5799561,0.3603516,0.5799561,1.2001953,0,1.5600586   l-2.5500488,1.5600586c-0.6099854,0.3701172-1.3900146-0.0698242-1.3900146-0.7797852V47.880127z"
              />
              <path
                fill="#07bf67"
                d="M26.2400513,21.6799316H52.000061c0.5599365,0,1-0.449707,1-1c0-0.5498047-0.4400635-1-1-1H26.2400513   c-0.5500488,0-1,0.4501953-1,1C25.2400513,21.2302246,25.6900024,21.6799316,26.2400513,21.6799316z"
              />
              <path
                fill="#07bf67"
                d="M26.2400513,26.9802246h14.0799561c0.5599365,0,1-0.4501953,1-1c0-0.550293-0.4400635-1-1-1H26.2400513   c-0.5500488,0-1,0.449707-1,1C25.2400513,26.5300293,25.6900024,26.9802246,26.2400513,26.9802246z"
              />
              <path
                fill="#07bf67"
                d="M26.2400513,34.5202637H52.000061c0.5599365,0,1-0.4501953,1-1c0-0.5600586-0.4400635-1-1-1H26.2400513   c-0.5500488,0-1,0.4399414-1,1C25.2400513,34.0700684,25.6900024,34.5202637,26.2400513,34.5202637z"
              />
              <path
                fill="#07bf67"
                d="M26.2400513,39.8200684h14.0799561c0.5599365,0,1-0.449707,1-1c0-0.5498047-0.4400635-1-1-1H26.2400513   c-0.5500488,0-1,0.4501953-1,1C25.2400513,39.3703613,25.6900024,39.8200684,26.2400513,39.8200684z"
              />
              <path
                fill="#07bf67"
                d="M26.2400513,48.0598145h12.1599121c0.5500488,0,1-0.449707,1-1c0-0.5498047-0.4499512-1-1-1H26.2400513   c-0.5500488,0-1,0.4501953-1,1C25.2400513,47.6101074,25.6900024,48.0598145,26.2400513,48.0598145z"
              />
              <path
                fill="#07bf67"
                d="M26.2400513,53.3601074h7.6599121c0.5500488,0,1-0.4501953,1-1c0-0.550293-0.4499512-1-1-1h-7.6599121   c-0.5500488,0-1,0.449707-1,1C25.2400513,52.9099121,25.6900024,53.3601074,26.2400513,53.3601074z"
              />
              <path
                fill="#07bf67"
                d="M64.0700073,52.4401855l-3.6700439,1.25c-0.0297012-0.1451454,0.2607231-1.980896-1.3599854-3.2299805V8.2302246   c0-3.4399414-2.7999268-6.2402344-6.2399902-6.2402344H7.7200317c-3.4400635,0-6.2399902,2.800293-6.2399902,6.2402344v45.6196289   c0,3.4404297,2.7999268,6.2402344,6.2399902,6.2402344h31.5999756v2.3999023c0,1.9399414,1.5799561,3.5200195,3.5198975,3.5200195   h14.0400391c1.9400635,0,3.5200195-1.5800781,3.5200195-3.5200195v-0.4599609l3.6700439,1.25   c1.1349792,0.4172287,2.4499512-0.4312553,2.4499512-1.75v-7.3398438   C66.5199585,52.8901978,65.231102,52.0250549,64.0700073,52.4401855z M52.500061,8.7902832   c0,1.0195313-0.8300781,1.8398438-1.8400879,1.8398438c-1.0200195,0-1.8399658-0.8203125-1.8399658-1.8398438   c0-1.0200195,0.8199463-1.840332,1.8399658-1.840332C51.6699829,6.9499512,52.500061,7.7702637,52.500061,8.7902832z    M47.1900024,8.7902832c0,1.0195313-0.8200684,1.8398438-1.8400879,1.8398438s-1.8399658-0.8203125-1.8399658-1.8398438   c0-1.0200195,0.8199463-1.840332,1.8399658-1.840332S47.1900024,7.7702637,47.1900024,8.7902832z M41.8799438,8.7902832   c0,1.0195313-0.8199463,1.8398438-1.8399658,1.8398438c-1.0100098,0-1.8299561-0.8203125-1.8299561-1.8398438   c0-1.0200195,0.8199463-1.840332,1.8299561-1.840332C41.0599976,6.9499512,41.8799438,7.7702637,41.8799438,8.7902832z    M21.9299927,9.0002441v0.0595703c0,0.8105469-0.6600342,1.4702148-1.4699707,1.4702148H9.500061   c-0.8100586,0-1.4700928-0.659668-1.4700928-1.4702148V9.0002441c0-0.8100586,0.6600342-1.4702148,1.4700928-1.4702148H20.460022   C21.2699585,7.5300293,21.9299927,8.1901855,21.9299927,9.0002441z M3.4800415,15.5100098H57.039978v34.2202148   c-0.0499268-0.0102539-0.1099854-0.0102539-0.1600342-0.0102539H42.8399048c-1.9399414,0-3.5198975,1.5703125-3.5198975,3.5200195   v4.8500977H7.7200317c-2.3400879,0-4.2399902-1.8999023-4.2399902-4.2402344V15.5100098z M45.9700317,55.1599121   c0-1.2299805,1.3399658-1.9799805,2.3798828-1.3398438l4.3400879,2.6601563   c0.9757843,0.5993881,0.9939003,1.9851036,0.0799561,2.6098633c-0.3038063,0.2033615-4.5201492,2.7810745-4.4200439,2.7197266   c-1.039917,0.6401367-2.3798828-0.1098633-2.3798828-1.3398438C45.9700317,58.5670357,45.9700317,57.072628,45.9700317,55.1599121z   "
              />
            </g>
          </svg>
          Watch List
        </h1>
        <br />
        <ShowCollection
          ShowList={SuggestionsCollection}
          CrossButtonStatus={true}
          CrossButtonFunction={RemoveFromList}
        />
      </main>
      <Footer />
    </>
  );
};

export default WatchList;
